### ISSUE TITLE
Image Selector - No notification about unsaved changes after an image was removed

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#310] opened 2017-11-27 13:41 UTC
1. Open a wizard for ImageSelector (2:4) content
2. Insert two requred images and save the content.
3. Do not close the content and select on e of the images and remove it
4. Do not press on the Save button but click on the 'close'-tab button 

BUG: Save Before Close dialog should appear, when there are unsaved changes - image was revoved.

**Comment by alansemenov** [comment] 2017-12-08 14:59
Duplicate of #340

**Closed** 2017-12-08 14:59 UTC
Labels: Bug, Duplicate, Not in Changelog
