### ISSUE TITLE
Console errors when trying to close a User Wizard tab with unsaved changes and empty fields

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#45] opened 2017-09-22 08:29 UTC
1. open Role wizard or Store wizard or Group wizard
2. do not type a name but type a discription for role or change Permissions for the Store
3. do not save it but click on the Close tab button 
4. click on Yes on the ConfirmationDialog
BUG: error i nthe console and exception in the Server.log
![role-wiz](https://user-images.githubusercontent.com/3728712/30735896-46b87d3a-9f89-11e7-90fa-03f720a971ac.png)

**Comment by alansemenov** [comment] 2017-09-27 14:04
@edloidas please check if this one is still relevant

**Comment by edloidas** [comment] 2017-09-28 09:06
@alansemenov Can't reproduce.

BTW we have a little bit strange checks before showing the `SaveBeforeClose` dialog now. We check the description (and some other fields) change only if the principal was already created, and don't check it for new items. It's the behavior we have for a long time, though.

**Comment by alansemenov** [comment] 2017-09-28 10:29
@edloidas I can reproduce it. Here's the correct order of steps:
1. Create a Role
2. Select a member from the "Members" dropdown
3. Try to close the tab
4. Click Yes in the confirmation

**Comment by alansemenov** [comment] 2017-09-28 10:41
1. Please fix it so that the dialog comes up whenever there's any change in the form (also for a new principal). Now a change in the Description field for a new Role doesn't seem to trigger it, for example.
2. There's at least one more bug here that involves form validation. When I create a new Role, I'm not allowed to save the form with empty mandatory fields (Save is disabled). However, if I open an *existing* role and remove the display name, "Save" doesn't get disabled and I can save a role with empty name (no validation on the server either).
3. We should fix the console errors when user tries to submit a form with empty mandatory fields (what the original bug describes)

**Comment by alansemenov** [comment] 2017-09-29 10:10
I'm moving this out of 6.12

**Closed** 2017-10-24 08:35 UTC
Labels: Bug
