### ISSUE TITLE
Error in the browser, when insert an image in the PageComponentView

### ISSUE THREAD

**Issue by sgauruseu** [enonic/xp-apps#474] opened 2018-01-14 08:28 UTC
1. Open site and open the PageComponentView
2. Select Insert Image menu item in the page component view
3. Select an image in the dropdown-options
BUG error appears

`_all.js:27484 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at removeRowFromCache (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1515917800/admin/common/lib/_all.js:27484:20)
    at updateRowCount (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1515917800/admin/common/lib/_all.js:27611:11)
    at SlickGrid.resizeCanvas (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1515917800/admin/common/lib/_all.js:27586:7)
    at Grid.resizeCanvas (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1515917800/admin/common/js/_all.js:24675:36)
    at updateColumnsHandler (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1515917800/admin/common/js/_all.js:27000:45)
    at ResponsiveItem.handler (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1515917800/admin/common/js/_all.js:27014:29)
    at ResponsiveItem.update (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1515917800/admin/common/js/_all.js:16224:38)
    at listener (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1515917800/admin/common/js/_all.js:16298:44)
    at ResponsiveManager.fireResizeEvent (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.ap`

<img width="926" alt="view" src="https://user-images.githubusercontent.com/3728712/34914170-0a23d402-f91e-11e7-81f4-ade3b149c048.png">

**Comment by alansemenov** [comment] 2018-01-15 10:34
I cannot reproduce this one. Most likely fixed in https://github.com/enonic/xp-apps/issues/447

**Closed** 2018-01-15 12:56 UTC
Labels: Bug, Can't Reproduce
